const products = [
  {
    id: 1,
    title: "Gradient Graphic T-shirt",
    price: 145,
    oldPrice: 0,
    discount: 0,
    rating: 3.5,
    img: "./img/page__img1.svg",
  },
  {
    id: 2,
    title: "Polo with Tipping Details",
    price: 180,
    oldPrice: 0,
    discount: 0,
    rating: 4.5,
    img: "./img/page__img2.svg",
  },
  {
    id: 3,
    title: "Black Striped T-shirt",
    price: 120,
    oldPrice: 150,
    discount: 30,
    rating: 5.0,
    img: "./img/page__img3.svg",
  },
  {
    id: 4,
    title: "Skinny Fit Jeans",
    price: 240,
    oldPrice: 260,
    discount: 20,
    rating: 3.5,
    img: "./img/page__img4.svg",
  },
  {
    id: 5,
    title: "Checkered Shirt",
    price: 180,
    oldPrice: 0,
    discount: 0,
    rating: 4.5,
    img: "./img/page__img5.svg",
  },
  {
    id: 6,
    title: "Sleeve Striped T-shirt",
    price: 130,
    oldPrice: 160,
    discount: 30,
    rating: 4.5,
    img: "./img/page__img6.svg",
  },
  {
    id: 7,
    title: "Vertical Striped Shirt",
    price: 212,
    oldPrice: 232,
    discount: 20,
    rating: 5.0,
    img: "./img/page__img7.svg",
  },
  {
    id: 8,
    title: "Courage Graphic T-shirt",
    price: 145,
    oldPrice: "0",
    discount: 0,
    rating: 4.0,
    img: "./img/page__img8.svg",
  },
  {
    id: 9,
    title: "Loose Fit Bermuda Shorts",
    price: 80,
    oldPrice: 0,
    discount: 0,
    rating: 3.0,
    img: "./img/page__img9.svg",
  },
];

let topproducts = [
  {
    id: 7,
    title: "Vertical Striped Shirt",
    price: 212,
    oldPrice: 232,
    discount: 20,
    rating: 5.0,
    img: "./img/page__img7.svg",
  },
  {
    id: 8,
    title: "Courage Graphic T-shirt",
    price: 145,
    oldPrice: 0,
    discount: 0,
    rating: 4.0,
    img: "./img/page__img8.svg",
  },
  {
    id: 9,
    title: "Loose Fit Bermuda Shorts",
    price: 80,
    oldPrice: 0,
    discount: 0,
    rating: 3.0,
    img: "./img/page__img9.svg",
  },
  {
    id: 4,
    title: "Skinny Fit Jeans",
    price: 240,
    oldPrice: 260,
    discount: 20,
    rating: 3.5,
    img: "./img/page__img4.svg",
  },
];
